### ISSUE TITLE
Use twig as template language

### ISSUE THREAD

**Issue by rafaellyra** [nickberens360/atomic-docs#13]
To improve the code readability and reusability we should use a template engine, I think that [twig](http://twig.sensiolabs.org/) has good standards and can fits good for us.

**Comment by gavmck** [comment]
+1 for this, we would like to build atomic docs into our Timber boilerplate.
https://github.com/timber/timber

**Comment by nickberens360** [comment]
@gavmck this issue is in reference to using twig as a templating language for the app itself. 

You can configure the components to use the .twig extension in the atomic-config.php file. Then it would just be a matter of using atomic-core/head.php as an entry point for your data. I do [this](http://atomicdocs.io/docs/wordpress) all the time for a standard install of wordpress. I've never worked with the Timber plugin however so I'm not sure how that would work. 

If you decide to try and you figure it out please let me know!

**Comment by gavmck** [comment]
Awesome! We are going to run a boilerplate hackday in a few weeks and will be building this in. Will let you know how it goes. Thanks!

**Comment by yumyo** [comment]
Hey @gavmck how was your hackday then? Would you like to share any of your findings or perhaps have you already done it elsewhere?

**Comment by gavmck** [comment]
We didn't have much luck with any of the pattern lab atomic design
styleguides unfortunately :(

I've recently been working with react-styleguideist and have ported some of
their ideas over to a custom twig styleguide we have running on our
WordPress and laravel boilerplates.

I'm hoping to push that over to open source shortly.

**Comment by alicam** [comment]
@gavmck Any progress on the styleguides/TWIG/WordPress??

**Comment by gavmck** [comment]
I've now left the company, but they are using this: https://github.com/RedBullet/generator-twig-component-library

Runs on twig, pretty easy to plug in to wordpress or laravel
