### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by prolax** [nickberens360/atomic-docs#4]
Ran it using both XAMP and WAMP - neither worked. 

It ran somewhat, trying to view the 'scss' tab would go to a white screen which said "Set up in your php local environment and configure your sass preprocessor and start here".

The .scss was compiling tho, I could change the colour of the box just fine.

Any ideas what I can do to get it running?

Also when clicking "add module" or any type of "add" button, the next page with the input fields have no styles for me either.

**Comment by alexanderdegre** [comment]
I'd also like to use this tool, so I downloaded it, also found it's pretty broken, and decided to look into what exactly is broken and why.

Currently `atomic-core/footer.php` is trying to include `atomic-core/js/min/compiled.min.js` but this file was gitignored in commit `6d42386` on April 13. Because of this, and with no instruction on what to use for JS compilation, no Javascript is included and thus the "add" pages are wonky. I replaced the JS include with the following:

`<script src="atomic-core/js/bootstrap.min.js"></script>
<script src="atomic-core/js/prism.js"></script>
<script src="atomic-core/js/uncomment.js"></script>
<script src="atomic-core/js/velocity.js"></script>
<script src="atomic-core/js/velocity-ui.js"></script>
<script src="atomic-core/js/_expand-form.js"></script>
<script src="atomic-core/js/_sidebar-show-hide.js"></script>
<script src="atomic-core/js/formShowHide.js"></script>
<script src="atomic-core/js/_actionDrawer.js"></script>
<script src="atomic-core/js/hideAll.js"></script>
<script src="atomic-core/js/hideCode.js"></script>
<script src="atomic-core/js/hideNotes.js"></script>
<script src="atomic-core/js/hideTitle.js"></script>
<script src="atomic-core/js/navSmall.js"></script>
<script src="atomic-core/js/animateHeight.js"></script>
<script src="atomic-core/js/global.js"></script>`

This works, but some of the javascript here is _also_ buggy (some undefined errors etc). For the most part it works.

The next issue is that you'll be able to see what the SCSS source is when clicking the SCSS tab for a given module, but the HTML source is blank. An include string is used for the detail page which dynamically writes php `include()` lines in order to load the source of the SCSS and HTML into a `<pre>` tag. This is done in `atomic-core/partial-mngr/functions/file-create-functions.php` in the method `createIncludeString()`. Unfortunately while the SCSS is included here, it seems including the HTML markup in its own `<pre>` for its own tab panel is just plain missing.


I'm not sure if the devs for this project plan to have a stable branch, or what the stability of the 1.0 tag is, but the master branch in its current state is basically unusable.

**Comment by nickberens360** [comment]
@prolax @alexanderdegre Hey guys, yeah I had added the compiled js to the gitignore while I was doing some work and forgot to remove it when I pushed my changes, oops. I added it back and everything should be working again. If you guys have time I'd really appreciate it if you could give it another try. Thanks!

**Comment by prolax** [comment]
works great now, thanks!

**Comment by nickberens360** [comment]
@prolax thanks for hanging in there with me! I had a coworker test it out and he was having a similar issue. It turns out his ad blocker was flagging one of my CSS class names. "ad_label". I refactored that class name and now things are working as they should. Are you running an ad blocker?

Would you mind pulling the latest code and trying again? Perhaps try it in an incognito window in Chrome.

**Comment by prolax** [comment]
@nickberens360 awesome job, works like a charm now :+1:
