### ISSUE TITLE
#atomsWrap CSS prevent previewing bootstrap elements

### ISSUE THREAD

**Issue by florentcm** [nickberens360/atomic-docs#43]
When editing atoms and using bootstrap, we cannot preview correctly some elements like ".form-control" inside atomic-core because the CSS stylesheet site.css define them under #atomsWrap applied to the body.

I suggest to exclude anything under ".source" class in site.css to be able to preview correctly these elements. Is there any other quickier solutions to achive this?

**Comment by nickberens360** [comment]
@florentcm The class name conflicts "should" be fixed in the update I just did. you can update your project by replacing the directory "atomic-core" in your project with the latest "atomic-core" directory from the repo. Just make sure and keep your old "atomic-core" directory until you verify everything is working as it should.

Thanks for checking out the project!

**Comment by florentcm** [comment]
Thank you, We really appreciate the update and we will continue to follow the development of Atomic-docs since we're starting using the atomic methodology.

**Comment by nickberens360** [comment]
@florentcm Good to hear. And thanks for the feedback!
